sonar.projectKey=AlexeyGribchenko_testmodule
sonar.organization=alexey-gribchenko

sonar.projectName=testmodule
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=**/*_test.go,README.md,.gitignore,go.mod,go.sum,sonar-project.properties,cmd/summator/main.go

sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=cov.out