sonar.projectKey=AlexeyGribchenko_testmodule
sonar.organization=alexey-gribchenko
sonar.projectName=testmodule

sonar.sources=.
sonar.exclusions=**/*_test.go

sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=cov.out
